// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DepartmentContext))]
    [Migration("20230826115510_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 8, 26, 14, 55, 9, 957, DateTimeKind.Local).AddTicks(8270),
                            Description = "Handles all engineering stuff",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2023, 8, 26, 14, 55, 9, 957, DateTimeKind.Local).AddTicks(8330),
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 8, 26, 14, 55, 9, 957, DateTimeKind.Local).AddTicks(8340),
                            Description = "Human Resources",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2023, 8, 26, 14, 55, 9, 957, DateTimeKind.Local).AddTicks(8340),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2023, 8, 26, 14, 55, 9, 957, DateTimeKind.Local).AddTicks(8340),
                            Description = "Handles financial matters",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2023, 8, 26, 14, 55, 9, 957, DateTimeKind.Local).AddTicks(8340),
                            Name = "Finance"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
